config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'surveys#index'
  resources :surveys do
    resources :questions
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  validates :body, presence: true
end  

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  validates :topic, presence: true
  before_save(:titleize_survey)

  private
  def titleize(user_input)
    input_array = []
    user_input = user_input.split(' ')
    user_input.each do |word|
      input_array.push((word.capitalize))
    end
    input_array.join(' ')  
  end    

  def titleize_survey
    self.topic = self.topic.titleize
  end  
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @survey = Survey.find(params[:id])
    @question = @survey.questions.new
    render :new
  end

  def create
    @survey = Survey.find(params[:id])
    @question = @survey.questions.new(question_params)
    if @question.save
      flash[:notice] = "Question Successfully Added!"
    else
      flash[:alert] = "There was an error while creating this question."
    end  
  end

  def edit
    @survey = Survey.find(params[:id])
    @question = Question.find(params[:id])
    render :edit
  end

  def show
    @survey = Survey.find(params[:id])
    @question = Question.find(params[:id])
    render :show
  end

  def update
    @question = Question.find(params[:id]) 
    if @question.update(question_params)
      flash[:notice] = "Question Updated!"
      redirect_to survey_path(@question.survey)
    else
      flash[:alert] = "An error occurred while updating the question"
      render :edit  
    end  
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Question Successfully destoryed"
  end

  private
    def question_params
      params.require(:question).permit(:body, :survey_id)
    end  

end  

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
    render :index
  end

  def new
    @survey = Survey.new
    render :new
  end

  def create
   @survey = Survey.new(survey_params)
   if @survey.save
    flash[:notice] = "Survey reated Successfully!"
    redirect_to surveys_path
   else
    flash[:alert] = "An error occurred while creating the survey."
    render :new
   end  
  end

  def edit
    @survey = Survey.find(params[:id])
    render :edit
  end

  def show
   @survey = Survey.find(params[:id])
   render :show
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      flash[:notice] = "Survey Updated Successfully!"
      redirect_to surveys_path
      flash[:alert] = "There was an error processing your request."
    end    
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    flash[:notice] = "YOU DESTROYED THAT SURVEY"
    redirect_to surveys_path
  end


  private
    def survey_params
      params.require(:survey).permit(:topic)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_survey_form.html.erb
<%= render "layouts/errors", :object => @survey %>

<%= form_for @survey do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "layouts/question_form" %>

app/views/questions/new.html.erb
<h1>Add a new question:</h1>

<%= form_for [@survey, @question] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <p><%= f.submit %></p>
<% end %>

app/views/questions/show.html.erb
<h1>Question: <%= @question.body %></h1>
<h2>Survey: <%= @survey.topic %></h2>

<p><%= link_to "Edit question", edit_survey_question_path(@survey, @question) %></p> <!--Note that we're passing two instance variables into our link_to helper methods. This is expected. We only need one for the survey_path, though. The prefix makes it clear which objects need to be passed into the path. -->
<p><%= link_to "Delete question", survey_question_path(@survey, @question),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to survey", survey_path(@survey) %></p>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% if @surveys.any? %>
  <ul>
    <% @surveys.each do |survey| %>
      <li><%= link_to survey.topic, survey_path(survey) %></li> <!--survey_path(survey). survey_path must take an argument because otherwise our application won't be able to route to a specific survey. -->
    <% end %>
  </ul>
<% else %>
  <p>There are no Surveys yet.</p>
<% end %>


<p><%= link_to "Create new Survey", new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.topic %></h1>

<% if @survey.questions.any? %>
  <h4>Here are the questions for this survey:</h4>

  <% @survey.questions.each do |question| %>
    <ul>
      <li>
        <%= link_to question.topic, survey_question_path(@survey, question) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No questions are listed for this survey.</p>
<% end %>

<p><%= link_to "Add a question", new_survey_question_path(@survey) %></p>

<p><%= link_to "Edit", edit_survey_path(@survey) %></p>
<p><%= link_to "Delete survey", survey_path(@survey),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to surveys", surveys_path %></p>